spring.datasource.url=jdbc:postgresql://localhost:5432/smart_canteen_db
spring.datasource.username=yashikasinha
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
